language: java
jdk:
  - oraclejdk8
  
before_install:
  - chmod +x mvnw

script: mvn clean test jacoco:report

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: ai-curriculum-vitae

after_success:
  - mvn coveralls:report
